# Generated by Django 4.2.8 on 2024-02-12 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_name', models.CharField(max_length=64)),
                ('ranking_num', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
                ('app_name', models.CharField(max_length=64)),
                ('download_value', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(fields=('ranking_name', 'rank'), name='unique_ranking_name_rank'),
        ),
    ]
